### PR TITLE
Some fixes in multiple comments

### PR DESCRIPTION
**Pull request by ingwarsw**
- Shortened crc
- Fixed NPE when no comments found

### CODE REVIEW

**Comment by ingwarsw** [comment]
From:
[Checkstyle] WARNING: Expected @param tag for 'tresc'.
crc:4d7a6b6757304e6f5a574e72633352356247566449466442556b354a546b6336494556346347566a6447566b4945427759584a6862534230595763675a6d397949436430636d567a59796375

To:
[Checkstyle] WARNING: Expected @param tag for 'tresc'. (fffffd04)

**Comment by ingwarsw** [comment]
But I still dont like format :(

**Comment by zygm0nt** [comment]
Thanks, will look into the whole issue + changes from pull request review from origin.

**Comment by zygm0nt** [comment]
sample comment

**Pull request merged**
